### ISSUE TITLE
Error fitDTU : Error in if (m == 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by TolgaDuz** [statOmics/satuRnPaper#2] opened 2023-04-15 13:38 UTC
Hi Jeroen,

thanks for this tool! 

I tried to follow the main vignette with my own dataset, but encountered the error mentioned above, after running fitDTU.
Can you help me out here? Maybe you can reproduce the error?

my expression matrix:
[merged_TPM_saturn.txt](https://github.com/statOmics/satuRnPaper/files/11239601/merged_TPM_saturn.txt)

my meta_file:
[meta_saturn.txt](https://github.com/statOmics/satuRnPaper/files/11239603/meta_saturn.txt)

my code:
[saturn.txt](https://github.com/statOmics/satuRnPaper/files/11239612/saturn.txt)

The data comes from GRCh37.p13, but i fetch for GRCh38. But I gues this shouldnt interfere with the overall functionality.

Looking really forward!

Cheers

**Comment by jgilis** [comment] 2023-04-16 10:17
Hi @TdzBAS,

I will try to reproduce the error you mentioned tomorrow.

Would you mind reposting your issue on the github page of the satuRn package https://github.com/statOmics/satuRn, in stead of here which is the repository of satuRn paper? I will close the issue here and provide my answers on your repost there, because it will be easier for others to find it there.

Best regards,


Jeroen

**Closed as completed by jgilis** 2023-04-16 10:17 UTC

**Comment by TolgaDuz** [comment] 2023-04-16 10:26
Hi @jgilis ,

Of course, sorry! Just did it!

thanks a lot!

Best,

Tolga
